### PR TITLE
Update deprecated Discord.js function calls

### PR DESCRIPTION
**Pull request by Fox-Islam**
- Updated discord.js from 12.1.1 to 12.5.1
- Updated deprecated function calls
- Modified `requires` to work with example apiconfig.json from
README
- Also escaped prefix backticks so that strings don't get
code-formatted when they're not meant to

### CODE REVIEW

**Comment by Fox-Islam** [comment]
Unfortunately the one thing I was unable to test was the papago integration since I don't have (and am unable to get) Naver API credentials, but hopefully these images make the current state of the bot's functionality clear enough (even with my silly test bot name):

helptext
help_word
help_hanja
help_examples
help_papago
word
hanja
examples
dm

**Comment by Fox-Islam** [comment]
Fixes issues:
Sejong bot has stopped functioning (https://github.com/jarjumarvin/sejong-bot/issues/9)
npm start error (https://github.com/jarjumarvin/sejong-bot/issues/3)

**Comment by jarjumarvin** [comment]
Oh wow! Thank you so much for this, I will have a look tomorrow and merge the request. For some reason I did not get a notification for this hence I am seeing it this late :( I appreciate your having a look a lot!

**Comment by Fox-Islam** [comment]
Was able to test the papago functionality by making my own pretend papago server, allowed me to fix the config import, here it is working:
image

**Comment by Fox-Islam** [comment]
> Oh wow! Thank you so much for this, I will have a look tomorrow and merge the request. For some reason I did not get a notification for this hence I am seeing it this late :( I appreciate your having a look a lot!

Ahh! This response came out of nowhere, I _just now_ got that bit of papago functionality working 😅 It's all good, hopefully it isn't too much of a pain to review, feel free to ask me any questions you have about it!

**Comment by jarjumarvin** [comment]
Hey I'll have a look now. In the meantime, feel free to join this makeshift discord server I just created so we can have a bit of a better way of communicating! https://discord.gg/9p7sFZ5d

**Comment by jarjumarvin** [comment]
I've merged the request after going thru it and testing it; The papago feature I'll check out another time and have disabled it for the time being :) Thanks again a lot feel free to shoot me a DM on discord @ Marvin#1997 anytime.

**Pull request merged**
